plugins:
    - prettier
extends:
    - airbnb
    - prettier
    - prettier/react
globals:
    graphql: true
rules:
    prettier/prettier: error
settings:
    import/resolver:
        node:
            paths:
            - "."
    import/core-modules: ['react', 'react-helmet']
