plugins:
    - prettier
    - react-hooks
env:
    browser: true
extends:
    - airbnb
    - prettier
    - prettier/react
globals:
    graphql: true
rules:
    prettier/prettier: error
    react-hooks/rules-of-hooks: error
    react-hooks/exhaustive-deps: error
settings:
    import/resolver:
        node:
            paths:
            - "."
    import/core-modules: ['react', 'react-helmet']
